### PR TITLE
feat: add universal builds for darwin

### PR DESCRIPTION
**Pull request by Lunchb0ne**
Had to remove the electron mirror as it didn't have darwin arm64 builds

### CODE REVIEW

**Comment by Lunchb0ne** [comment]
Not sure if the mirror is too essential for working, so I'd just like to make sure it's still working fine when compiling on other architectures.

**Comment by ThaUnknown** [comment]
it is essential so you can't remove it

**Comment by Lunchb0ne** [comment]
To make a universal build we'll need an arm64 release of electron too. What exactly is special about the custom electron? Can we add an arm64 release for it?

**Comment by ThaUnknown** [comment]
to my knowledge electron arm builds for macos don't even work

**Comment by Lunchb0ne** [comment]
Weird the action fails, I was able to build a universal version of the app locally.

**Comment by ThaUnknown** [comment]
marking this as stale, as the PR itself is broken, and the reason for needing universal darwin builds isn't explained

this PR also breaks the app, but that's mostly my fault as Miru doesn't have any tests because I was too lazy to implement them :^)

**Comment by ThaUnknown** [comment]
this PR is broken, stale, and doesn't explain the need for universal darwin builds

**Comment by ThaUnknown** [comment]
addressed and fixed in:
3d05c598bfa26e38010267e81e9cb41686cd66d1
8bce6e0945f8f78401da124195c3c7521484eca3
cf28d565c1187bd11272f0c485632f773958067d
435d8aa52ca9ec300fd4dcb10176e35c38a43385

**Pull request closed without merging**
