### PR TITLE
 Fix app icon for linux and macOS

### PR DESCRIPTION
**Pull request by Muril-o**
This fixes .deb app icon for linux and (hopefully) macOS.
Tested on Ubuntu 20.04 LTS and Debian, need testing on macOS if that was even a problem in the first place and/or if its fixed now.
Note from [here](https://www.electron.build/icons.html#linux).
> Linux icon set will be generated automatically based on the macOS icns file

### CODE REVIEW

**Comment by ThaUnknown** [comment]
don't you also need to include the icon file in /build?

**Comment by Muril-o** [comment]
> don't you also need to include the icon file in /build?

Its already there?

**Comment by ThaUnknown** [comment]
not the icon.icns ??

**Comment by Muril-o** [comment]
> not the icon.icns ??

image

**Comment by ThaUnknown** [comment]
FUuu
i need sleep

**Pull request merged**
