### PR TITLE
Added images for recent Flathub PR

### PR DESCRIPTION
**Pull request by Angxddeep**
### So In order to update images on [PR](https://github.com/flathub/io.github.thaunknown.miru/pull/99) this Pull Request needs to be added

### CODE REVIEW

**Comment by Angxddeep** [comment]
@ThaUnknown Any update on this, are you going to Merge it or any other concern that you might have?

**Comment by Angxddeep** [comment]
@ThaUnknown Any chance you will merge this or any questions you might have. This PR been siting here for a week now :)

**Comment by ThaUnknown** [comment]
I'm on vacation

**Comment by Angxddeep** [comment]
> I'm on vacation

Oh, Enjoy your vacation 🥳

**Comment by ThaUnknown** [comment]
but from what I can see I'd need to manually release each version of flatpak myself, I ain't doing that, it needs to be automated, just like winget

**Comment by Angxddeep** [comment]
That is possible but requires a lot more knowledge of Flatpaks TBH, And also requires signing keys and stuff, there is a lot more that you have to do on your end to make it possible. As you said about the manually merge thing, it will be just the PR created by the flathub-bot, That you have to manually merge.

**Comment by ThaUnknown** [comment]
yes, as I said that's a no go, it needs to be automated

**Comment by Angxddeep** [comment]
OK, I will look into how to automate this

**Comment by ThaUnknown** [comment]
it's just extra work, imagine every package manager needed a manual release like that, it would be hell on earth

**Comment by Angxddeep** [comment]
Yeah, packaging stuff is a mess, that's what snaps and flatpak are trying to solve in the Linux space by making one packaging format that runs on all distros, but things are still pretty early. It will take time to adopt a single or in this case a double standard.

**Comment by Angxddeep** [comment]
@ThaUnknown So, I talked to the Lead flahub dev he says if we can get the app verified then it will automerge the pull request created by flathub-bot. For Verification, follow [this](https://docs.flathub.org/docs/for-app-authors/verification) guide once your app is verified it will automate the release process also the verification plays an important rope in raising the popularity of the app

**Comment by Angxddeep** [comment]
Also after the app get verified there is a linter exception that needs to be added to flahub-builder, but I will manage that by myself

**Comment by Angxddeep** [comment]
Also, I will personally recommend closing the two PRs first, so that it builds a new flatpak with a new version, then apply for verification if possible.(and enjoy your vacation first 😜)

**Comment by Angxddeep** [comment]
@ThaUnknown If you don't mind, can I maintain the flathub package of miru. I remember you mentioned before that you're not really into Linux, so if you're okay with it, I'll reach out to the Flathub team to get access :)

**Comment by ThaUnknown** [comment]
knock yourself out, as long as you don't modify the underlying dependencies miru ships and don't modify the code I'm okay with any package manager out there

**Comment by Angxddeep** [comment]
@ThaUnknown So, I just got access to flathub repo. You may close this PR now so i can build the flatpak version

**Comment by Angxddeep** [comment]
@ThaUnknown Sorry I wrote close, but what I mean was merge this PR I need these images to be in the repo

**Comment by ThaUnknown** [comment]
these images are of bad quality, use images from https://github.com/ThaUnknown/miru/tree/master/web/static

**Comment by Angxddeep** [comment]
Oh, I didn't know about that, but they prefer images taken on Linux, so It's better I Take them myself

**Pull request closed without merging**
