### PR TITLE
Fix for video not playing due to user not being logged in anilist

### PR DESCRIPTION
**Pull request by Muril-o**
Simple if else statement, can beautify if you want or create a separate function for it

### CODE REVIEW

**Comment by Muril-o** [comment]
Also, right now it's set to play the first episode, I have no clue if theres a localstorage for storing locally played episodes (not anilist synced).
Might want to store played episodes for an offline continue button, maybe also saving current time, but honestly that would be a lot of work to make do with torrent on the specific time location

**Comment by ThaUnknown** [comment]
right, the original function had error handling, let's do this differently, in rssview do
```js
export function playAnime(media, episode = 1){
```

**Comment by ThaUnknown** [comment]
tested if this fixed the underlying issue?

**Comment by ThaUnknown** [comment]
also, pls squash with PR title as i don't have semantic PRs yet

**Comment by ThaUnknown** [comment]
lgtm

**Pull request merged**
